### ISSUE TITLE
Are you planning on releasing the code?

### ISSUE THREAD

**Issue by Njasa2k** [damo-vilab/Cones-V2#1]

**Comment by Johanan528** [comment]
yes, we will release code in this week.

**Comment by dboshardy** [comment]
Are you still planning on releasing the code?

**Comment by wenhuchen** [comment]
What's the plan?

**Comment by earthseaon** [comment]
Do you still have open source code? Not only this project, but also Cones'.

**Comment by okaris** [comment]
Any plans on actually releasing the code for Cones and Cones2 ? @Johanan528

**Comment by nemonameless** [comment]
@Johanan528

**Comment by Johanan528** [comment]
Thanks for interest in our work, we have released our code.
