### ISSUE TITLE
Can not reproduce the results

### ISSUE THREAD

**Issue by Kyfafyd** [damo-vilab/Cones-V2#6]
Thanks for sharing the code!
I am trying to reproduce the composition of `dog` and `mug` by myself.
My training command is as the following:
```shell
accelerate launch train_cones2.py \
  --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1-base"  \
  --instance_data_dir="./data/dog" \
  --instance_prompt=dog \
  --token_num=1 \
  --output_dir="cones_v2_output/dog_image" \
  --resolution=768 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=4000 \
  --loss_rate_first=1e-2 \
  --loss_rate_second=1e-3 \
  --enable_xformers_memory_efficient_attention
```
Once trained, I use the `residual.pt` at 4000th iter for inference, using the following inference config:
```json
[
    {
        "prompt":"a mug and a dog on the beach",
        "residual_dict": {
            "dog":"cones_v2_output/dog_video/residual_3000.pt",
            "cat":"cones_v2_output/cat_image/residual.pt",
            "mug":"residuals/mug.pt",
            "flower":"residuals/flower.pt",
            "sunglasses":"residuals/sunglasses.pt",
            "lake":"residuals/lake.pt",
            "barn":"residuals/barn.pt"
        },
        "color_context":{
            "255,192,0":["mug",2.5],
            "255,0,0":["dog",2.5]
        },
        "guidance_steps":50,
        "guidance_weight":0.08,
        "weight_negative":-1e8,
        "layout":"layouts/layout_example.png",
        "subject_list":[["mug",2],["dog",5]]
    }
]
```

Then I get the generated image, and the `dog` is not promising (while the `mug` is good, using the provided `mug.pt`):
<img width="512" alt="image" src="https://github.com/damo-vilab/Cones-V2/assets/42490513/81297b5b-8b96-463a-a2ba-db21dd4bfb27">

However, using the provided `dog.pt`, I can get good results:
<img width="512" alt="image" src="https://github.com/damo-vilab/Cones-V2/assets/42490513/e50e98f2-0966-4aad-806f-f6aa171a0d65">

Could you please help me figure this out? Or is there any tips for obtaining good results?

**Comment by Johanan528** [comment]
Sorry to late reply, have you tried other prompts, or generated single dog using layout guidance?

**Comment by Kyfafyd** [comment]
Thanks for your response! All of the following results are using layout guidance.
With the prompt `A dog on the grass`, I get the following:
![image](https://github.com/damo-vilab/Cones-V2/assets/42490513/91e3083d-a329-46a4-99c5-3c821bb7a035)

With the prompt `Photo of a dog`, I get the following:
![image](https://github.com/damo-vilab/Cones-V2/assets/42490513/e764cb86-18cc-4412-9f59-8c2f8126d484)

Also, I have tried to decrease the lr to `2e-5` and increase the steps to `10000`, with the following `dog` and `mug`:
![image](https://github.com/damo-vilab/Cones-V2/assets/42490513/b624d598-696e-4d87-b6f2-c218037cf788)

**Comment by Johanan528** [comment]
It seems that the images you uploaded are damaged? I will retrain “dog” locally according to your command and see the results.

**Comment by Kyfafyd** [comment]
Sorry for that, I do not know why this happen... But I can view the images on the phone. Thanks for your response

**Comment by yy13138** [comment]
i got a error “TypeError: __init__() got an unexpected keyword argument 'debug'”， can you tell me the version for accelerate？ tk.

**Comment by yy13138** [comment]
I received same question. Used your pt file got great，But train result is fail.

This's my result.(a cat and a dog on the beach)
![all_images](https://github.com/damo-vilab/Cones-V2/assets/71684928/5bbb4525-9f24-4db3-a4bf-5dc374584717)

**Comment by Johanan528** [comment]
> Thanks for your response! All of the following results are using layout guidance. With the prompt `A dog on the grass`, I get the following: ![image](https://user-images.githubusercontent.com/42490513/272240033-91e3083d-a329-46a4-99c5-3c821bb7a035.png)
> 
> With the prompt `Photo of a dog`, I get the following: ![image](https://user-images.githubusercontent.com/42490513/272240522-e764cb86-18cc-4412-9f59-8c2f8126d484.png)
>

**Comment by Kyfafyd** [comment]
Any updates on this? 👀

**Comment by Johanan528** [comment]
Sry to late reply, we tried retraining the white dog and obtained satisfied results, but we did not use 'enable_xformers_memory_efficient_attention'. Have you tried training without enabling memory-efficient training?

**Comment by Kyfafyd** [comment]
> Sry to late reply, we tried retraining the white dog and obtained satisfied results, but we did not use 'enable_xformers_memory_efficient_attention'. Have you tried training without enabling memory-efficient training?

I have not tried trying without enabling memory-efficient because of OOM issue. Could you please show your re-trained results?

**Comment by Johanan528** [comment]
Here are some results：

![5](https://github.com/damo-vilab/Cones-V2/assets/56764880/1415568c-a951-43df-be9d-0d4e2fe1c206)
![12](https://github.com/damo-vilab/Cones-V2/assets/56764880/1d4243c9-8412-4d83-a246-9d343a391947)
